
package server;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteInstancia", targetNamespace = "http://server/")
public class NoExisteInstancia_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteInstancia faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteInstancia_Exception(String message, NoExisteInstancia faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteInstancia_Exception(String message, NoExisteInstancia faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.NoExisteInstancia
     */
    public NoExisteInstancia getFaultInfo() {
        return faultInfo;
    }

}
