
package server;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CamposVaciosExcepcion", targetNamespace = "http://server/")
public class CamposVaciosExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CamposVaciosExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CamposVaciosExcepcion_Exception(String message, CamposVaciosExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CamposVaciosExcepcion_Exception(String message, CamposVaciosExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.CamposVaciosExcepcion
     */
    public CamposVaciosExcepcion getFaultInfo() {
        return faultInfo;
    }

}
