
package server;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ElementoRepetidoException", targetNamespace = "http://server/")
public class ElementoRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ElementoRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ElementoRepetidoException_Exception(String message, ElementoRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ElementoRepetidoException_Exception(String message, ElementoRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: server.ElementoRepetidoException
     */
    public ElementoRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
